name: Deploy Flask App to Touge Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==8.4.1
          pytest tests/ -v
        continue-on-error: false
      - name: Deploy to Touge Server via SSH (Port 42687)
        run: |
          # 配置SSH环境
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # 使用base64解码私钥
          echo "$TOUGE_SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 添加服务器到known_hosts
          ssh-keyscan -p 42687 -H 47.96.157.89 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          echo "SSH环境配置完成，尝试连接服务器..."
          
          # 正式部署
          ssh -T -p 42687 \
              -o BatchMode=yes \
              -o StrictHostKeyChecking=yes \
              root@47.96.157.89 << 'EOF'
                set -e
                echo "成功连接服务器：$(whoami)@$(hostname)"
                
                # 添加GitHub的SSH主机密钥到known_hosts
                mkdir -p ~/.ssh
                chmod 700 ~/.ssh
                if ! grep -q "github.com" ~/.ssh/known_hosts 2>/dev/null; then
                    echo "添加GitHub SSH主机密钥..."
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    chmod 644 ~/.ssh/known_hosts
                fi
                
                cd /root/flask-web-app || { echo "项目目录不存在"; exit 1; }
                
                # 设置Git用户信息（避免警告）
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                
                # 使用SSH方式拉取
                echo "使用SSH方式拉取代码..."
                git remote set-url origin git@github.com:px-pq/flask-web-app.git
                
                # 拉取代码
                if ! git pull origin main; then
                    echo "Git拉取失败，尝试强制重置..."
                    git fetch --all
                    git reset --hard origin/main
                fi
                
                pip3 install --upgrade pip
                pip3 install -r requirements.txt || { echo "依赖安装失败"; exit 1; }
                
                supervisorctl restart flask-web-app || { echo "应用重启失败"; exit 1; }
                supervisorctl status flask-web-app
                echo "部署完成"
          EOF
        env:
          TOUGE_SSH_PRIVATE_KEY_BASE64: ${{ secrets.TOUGE_SSH_PRIVATE_KEY_BASE64 }}